### ISSUE TITLE
Compile errors in gcc

### ISSUE THREAD

**Issue by ids1024** [alberthdev/wxwabbitemu#3]
When I try to compile with gcc 6.1.1, the build fails with "narrowing conversion" errors: https://gist.github.com/ids1024/36f27e387376b92bc27e0062e78f9adc

It compiles successfully in clang.

**Comment by alberthdev** [comment]
Gotcha - what happens if you change

```
static const char TI_Icons_bmp[] = {
```

to:

```
static const char TI_Icons_bmp[] = (char *) {
```

Didn't get a chance to test this myself, so this might not even work... but let me know if it does!

**Comment by ids1024** [comment]
No, that doesn't seem to fix it.

**Comment by alberthdev** [comment]
I just pushed a few commits to master - they should hopefully fix your issue! (GCC on my side no longer spits out warnings that your compiler errored on...)

**Comment by ids1024** [comment]
Yes, that seems to have fixed it.
